version: "3.8"

services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archiveTeamWarrior
    restart: unless-stopped
    hostname: archiveTeamWarrior
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      - DOWNLOADER=Teddy55
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=3
  
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - ./data/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    volumes:
      - /path/to/data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: always
    volumes:
      - ./data/synapse:/data
    environment:
      VIRTUAL_HOST: "teddy55.com"
      VIRTUAL_PORT: 8008
      SYNAPSE_SERVER_NAME: "teddy55.com"
      SYNAPSE_REPORT_STATS: "yes"

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data/vaultwarden:/data
    environment:
      WEBSOCKET_ENABLED: "true"

networks:
  default:
    external: true
    name: proxynet