version: "3.8"

  services:
    netgame-bot:
      image: teddy55/netgame-bot:latest
      container_name: netgame-bot
      restart: always
      volumes:
        - ./data/netgame/:/WORKDIR/data
    
    ttt-bot:
      image: teddy55/ttt-bot:latest
      container_name: ttt-bot
      restart: always
      volumes:
        - ./data/ttt-bot/:/WORKDIR/data
  
    wohnzimmer-bot:
      image: teddy55/wohnzimmer-bot:latest
      container_name: wohnzimmer-bot
      restart: always
      volumes:
        - ./data/wohnzimmer-bot/:/WORKDIR/data

networks:
  default:
    external: true
    name: proxynet