version: "3.8"

services:
  smb-server:
    image: dperson/samba
    container_name: smb-server
    restart: unless-stopped
    

  smb-web:
    image: filebrowser/filebrowser
    container_name: smb-web
    restart: unless-stopped
    volumes:
      - /path/to/smb/root:/srv

networks:
  default:
    external: true
    name: proxynet